import Head from "next/head";
import { Fragment, useState } from "react";
import Image from "next/image";

import { Testimonials } from "../Components/Testimonials";

import ProductCards from "../Components/ProductCards";
import { Swiper, SwiperSlide } from "swiper/react";
import "swiper/css";
import "swiper/css/pagination";
import "swiper/css/navigation";
import { FiTruck } from "react-icons/fi";
import { FaExchangeAlt } from "react-icons/fa";
import { FiPercent } from "react-icons/fi";
import { Ri24HoursLine } from "react-icons/ri";
import b1 from "../styles/Images/brand-1.png";
import b2 from "../styles/Images/brand-2.png";
import b3 from "../styles/Images/brand-3.png";
import b4 from "../styles/Images/brand-4.png";
import b5 from "../styles/Images/brand-5.png";

import { FaChevronRight } from "react-icons/fa";
import { FaChevronLeft } from "react-icons/fa";


import { Pagination, Navigation } from "swiper";
import MainSlider from "../Components/MainSlider";
import Brands from "../Components/Brands";
import Dlivery from "../Components/Dlivery";
import axios from "axios";
import { Dialog, Disclosure, Menu, Transition } from "@headlessui/react";
import { XMarkIcon } from "@heroicons/react/24/outline";
import {
	ChevronDownIcon,
	FunnelIcon,
	MinusIcon,
	PlusIcon,
	Squares2X2Icon,
} from "@heroicons/react/20/solid";

import C1 from "../styles/Images/cart.jpg";
import C2 from "../styles/Images/cart-2.jpg";
import C3 from "../styles/Images/cart-3.jpg";
import C4 from "../styles/Images/cart-4.jpg";
const product = {
	slug: "Basic Tee 6-Pack",
	price: "$192",
	href: "#",
	brand: "Bonnza",
	images: [
		{
			src: C1,
			alt: "Two each of gray, white, and black shirts laying flat.",
		},
		{
			src: C2,
			alt: "Model wearing plain black basic tee.",
		},
		{
			src: C3,
			alt: "Model wearing plain gray basic tee.",
		},
		{
			src: C4,
			alt: "Model wearing plain white basic tee.",
		},
	],
};
const sortOptions = [
	{ name: "Most Popular", href: "#", current: true },
	{ name: "Best Rating", href: "#", current: false },
	{ name: "Newest", href: "#", current: false },
	{ name: "Price: Low to High", href: "#", current: false },
	{ name: "Price: High to Low", href: "#", current: false },
];
const subCategories = [
	{ name: "Totes", href: "#" },
	{ name: "Backpacks", href: "#" },
	{ name: "Travel Bags", href: "#" },
	{ name: "Hip Bags", href: "#" },
	{ name: "Laptop Sleeves", href: "#" },
];
const filters = [
	{
		id: "color",
		name: "Color",
		options: [
			{ value: "white", label: "White", checked: false },
			{ value: "beige", label: "Beige", checked: false },
			{ value: "blue", label: "Blue", checked: true },
			{ value: "brown", label: "Brown", checked: false },
			{ value: "green", label: "Green", checked: false },
			{ value: "purple", label: "Purple", checked: false },
		],
	},
	{
		id: "category",
		name: "Category",
		options: [
			{ value: "new-arrivals", label: "New Arrivals", checked: false },
			{ value: "sale", label: "Sale", checked: false },
			{ value: "travel", label: "Travel", checked: true },
			{ value: "organization", label: "Organization", checked: false },
			{ value: "accessories", label: "Accessories", checked: false },
		],
	},
	{
		id: "size",
		name: "Size",
		options: [
			{ value: "2l", label: "2L", checked: false },
			{ value: "6l", label: "6L", checked: false },
			{ value: "12l", label: "12L", checked: false },
			{ value: "18l", label: "18L", checked: false },
			{ value: "20l", label: "20L", checked: false },
			{ value: "40l", label: "40L", checked: true },
		],
	},
];
function classNames(...classes) {
	return classes.filter(Boolean).join(" ");
}
const Home = (props) => {
	 const [mobileFiltersOpen, setMobileFiltersOpen] = useState(false);
	return (
		<div>
			<Head>
				<title>Pakeeza Electronics</title>
				<meta name="description" content="Generated by create next app" />
				<link rel="icon" href="/favicon.ico" />
			</Head>
			<MainSlider />
			<Brands />
			<div className="bg-[#2b2a2a] h-[50rem] mt-[10rem]">
				<div className="container ">
					<h3 className="text-center text-yellow-600 mt-5 text-[32px] mt-5 pb=22 font-medium">
						New Arrivals
					</h3>
					<Swiper
						breakpoints={{
							640: {
								slidesPerView: 1,
							},
							768: {
								slidesPerView: 2,
							},
							1199: {
								slidesPerView: 3,
							},
						}}
						spaceBetween={30}
						freeMode={true}
						pagination={{
							clickable: true,
						}}
						navigation={{
							clickable: true,
						}}
						modules={[Pagination, Navigation]}
						className="mySwiper"
					>
						{props.productsData.data.map((item) => {
							let imgurl = "https://glacial-woodland-47482.herokuapp.com";
							let img =
								item.attributes.img.data.attributes.formats.thumbnail.url;
							// console.log(img);

							return (
								<SwiperSlide key={item.id}>
									<ProductCards
										slug={item.attributes.Model}
										name={item.attributes.Name}
										
										brands={item.attributes.Brand}
										price={item.attributes.Price}
										Picture={img}
										
									/>
									;
								</SwiperSlide>
							);
						})}
					</Swiper>
				</div>
			</div>

			<section class="container py-5">
				<div class="row">
					<div class="col-md-6 col-lg-3 pb-5">
						<div class="h-100 py-5 services-icon-wap shadow">
							<div class="h1 text-success text-center">
								{/* <i class="fa fa-truck fa-lg"></i> */}
								<div className="flex justify-center">
									<FiTruck color="#ffae42" />
								</div>
							</div>
							<h2 class="h5 mt-4 text-center">Delivery Services</h2>
						</div>
					</div>

					<div class="col-md-6 col-lg-3 pb-5">
						<div class="h-100 py-5 services-icon-wap shadow">
							<div class="h1 text-success text-center">
								<div className="flex justify-center">
									<FaExchangeAlt color="#ffae42" />
								</div>
							</div>
							<h2 class="h5 mt-4 text-center">Shipping & Return</h2>
						</div>
					</div>

					<div class="col-md-6 col-lg-3 pb-5">
						<div class="h-100 py-5 services-icon-wap shadow">
							<div class="h1 text-success text-center">
								<div className="flex justify-center">
									<FiPercent color="#ffae42" />
								</div>
							</div>
							<h2 class="h5 mt-4 text-center">Promotion</h2>
						</div>
					</div>

					<div class="col-md-6 col-lg-3 pb-5">
						<div class="h-100 py-5 services-icon-wap shadow">
							<div class="h1 text-success text-center">
								<div className="flex justify-center">
									<Ri24HoursLine color="#ffae42" />
								</div>
							</div>
							<h2 class="h5 mt-4 text-center">24 Hours Service</h2>
						</div>
					</div>
				</div>
			</section>

			<div className="container mt-[3rem]">
				<h2 className="text-center text-[32px] font-bold pb-[2rem] text-[#ffae42]">
					TOP CATEGORIES
				</h2>
			</div>
			<div className="bg-[#2b2a2a] h-[50rem] mt-[10rem]">
				<div className="conatiner mt-[4rem]">
					<p className="text-yellow-500 text-[30px] text-center">
						Premium Collections
					</p>
					<h3 className=" font-extrabold text-[40px] text-center pb-3  ml-5 text-white">
						AIR-CON & AIR COOLER
					</h3>
					<p className="text-center text-white text-[18px]">
						Details to details is what makes Hexashop different from the other
						themes
					</p>
					<Swiper
						breakpoints={{
							640: {
								slidesPerView: 1,
								spaceBetween: 30,
							},
							768: {
								slidesPerView: 2,
								spaceBetween: 30,
							},
							1199: {
								slidesPerView: 3,
								spaceBetween: -100,
							},
						}}
						freeMode={true}
						pagination={{
							clickable: true,
						}}
						navigation={{
							clickable: true,
						}}
						modules={[Pagination, Navigation]}
						className="mySwiper"
					>
						{props.productsData.data.map((item) => {
							let imgurl = "https://glacial-woodland-47482.herokuapp.com";
							let img =
								item.attributes.img.data.attributes.formats.thumbnail.url;

							return (
								<SwiperSlide key={item.id}>
									<ProductCards
										slug={item.attributes.Name}
										brands={item.attributes.Brand}
										price={item.attributes.Price}
										Picture={img}
										Model={item.attributes.Model}
									/>
									;
								</SwiperSlide>
							);
						})}
					</Swiper>
				</div>
			</div>

			{/* <Dlivery /> */}
			<div className="bg-[#2b2a2a] h-[50rem] mt-[10rem]">
				<div className="conatiner mt-[4rem]">
					<p className="text-yellow-500 text-[30px] text-center">
						Premium Collections
					</p>
					<h3 className=" font-extrabold text-[40px] text-center pb-3  ml-5 text-white">
						REFRIGERATOR & FREEZERS
					</h3>
					<p className="text-center text-white text-[18px]">
						Details to details is what makes Hexashop different from the other
						themes
					</p>
					<Swiper
						breakpoints={{
							640: {
								slidesPerView: 1,
							},
							768: {
								slidesPerView: 2,
							},
							1199: {
								slidesPerView: 3,
							},
						}}
						spaceBetween={30}
						freeMode={true}
						pagination={{
							clickable: true,
						}}
						navigation={{
							clickable: true,
						}}
						modules={[Pagination, Navigation]}
						className="mySwiper"
					>
						{props.FreezerData.data.map((item) => {
							let imgurl = "https://glacial-woodland-47482.herokuapp.com";
							let img =
								item.attributes.img.data.attributes.formats.thumbnail.url;
							// console.log(img);

							return (
								<SwiperSlide key={item.id}>
									<ProductCards
										slug={item.attributes.Name}
										Model={item.attributes.Model}
										brands={item.attributes.Brand}
										price={item.attributes.Price}
										Picture={img}
									/>
									;
								</SwiperSlide>
							);
						})}
					</Swiper>
				</div>
			</div>
			<div className="bg-[#2b2a2a] h-[50rem] mt-[10rem]">
				<div className="conatiner mt-[4rem]">
					<p className="text-yellow-500 text-[30px] text-center">
						Premium Collections
					</p>
					<h3 className=" font-extrabold text-[40px] text-center pb-3  ml-5 text-white">
						LED TV & SOUND SYSTEM
					</h3>
					<p className="text-center text-white text-[18px]">
						Details to details is what makes Hexashop different from the other
						themes
					</p>
					<Swiper
						breakpoints={{
							640: {
								slidesPerView: 1,
							},
							768: {
								slidesPerView: 2,
							},
							1199: {
								slidesPerView: 3,
							},
						}}
						spaceBetween={30}
						freeMode={true}
						pagination={{
							clickable: true,
						}}
						navigation={{
							clickable: true,
						}}
						modules={[Pagination, Navigation]}
						className="mySwiper"
					>
						{props.LEDData.data.map((item) => {
							let imgurl = "https://glacial-woodland-47482.herokuapp.com";
							let img =
								item.attributes.img.data.attributes.formats.thumbnail.url;
							// console.log(img);

							return (
								<SwiperSlide key={item.id}>
									<ProductCards
										slug={item.attributes.Model}
										name={item.attributes.Name}
										brands={item.attributes.Brand}
										price={item.attributes.Price}
										Picture={img}
									/>
									;
								</SwiperSlide>
							);
						})}
					</Swiper>
				</div>
			</div>
			<div className="bg-[#2b2a2a] h-[50rem] mt-[10rem]">
				<div className="conatiner mt-[4rem]">
					<p className="text-yellow-500 text-[30px] text-center">
						Premium Collections
					</p>
					<h3 className=" font-extrabold text-[40px] text-center pb-3  ml-5 text-white">
						HOME APPLIANCES
					</h3>
					<p className="text-center text-white text-[18px]">
						Details to details is what makes Hexashop different from the other
						themes
					</p>
					<Swiper
						breakpoints={{
							640: {
								slidesPerView: 1,
							},
							768: {
								slidesPerView: 2,
							},
							1199: {
								slidesPerView: 3,
							},
						}}
						spaceBetween={30}
						freeMode={true}
						pagination={{
							clickable: true,
						}}
						navigation={{
							clickable: true,
						}}
						modules={[Pagination, Navigation]}
						className="mySwiper"
					>
						{props.HomeData.data.map((item) => {
							let imgurl = "https://glacial-woodland-47482.herokuapp.com";
							let img =
								item.attributes.img.data.attributes.formats.thumbnail.url;
							// console.log(img);

							return (
								<SwiperSlide key={item.id}>
									<ProductCards
										slug={item.attributes.Model}
										name={item.attributes.Name}
										brands={item.attributes.Brand}
										price={item.attributes.Price}
										Picture={img}
									/>
									;
								</SwiperSlide>
							);
						})}
					</Swiper>
				</div>
			</div>
			<div className="bg-[#2b2a2a] h-[50rem] mt-[10rem]">
				<div className="conatiner mt-[4rem]">
					<p className="text-yellow-500 text-[30px] text-center">
						Premium Collections
					</p>
					<h3 className=" font-extrabold text-[40px] text-center pb-3  ml-5 text-white">
						BUILT-IN KITCHEN
					</h3>
					<p className="text-center text-white text-[18px]">
						Details to details is what makes Hexashop different from the other
						themes
					</p>
					<Swiper
						breakpoints={{
							640: {
								slidesPerView: 1,
							},
							768: {
								slidesPerView: 2,
							},
							1199: {
								slidesPerView: 3,
							},
						}}
						spaceBetween={30}
						freeMode={true}
						pagination={{
							clickable: true,
						}}
						navigation={{
							clickable: true,
						}}
						modules={[Pagination, Navigation]}
						className="mySwiper"
					>
						{props.KitchenData.data.map((item) => {
							let imgurl = "https://glacial-woodland-47482.herokuapp.com";
							let img =
								item.attributes.img.data.attributes.formats.thumbnail.url;
							// console.log(img);

							return (
								<SwiperSlide key={item.id}>
									<ProductCards
										slug={item.attributes.Model}
										name={item.attributes.Name}
										brands={item.attributes.Brand}
										price={item.attributes.Price}
										Picture={img}
									/>
									;
								</SwiperSlide>
							);
						})}
					</Swiper>
				</div>
			</div>
			<div className="bg-[#2b2a2a] h-[50rem] mt-[10rem]">
				<div className="conatiner mt-[4rem]">
					<p className="text-yellow-500 text-[30px] text-center">
						Premium Collections
					</p>
					<h3 className=" font-extrabold text-[40px] text-center pb-3  ml-5 text-white">
						WASHING SOLUTIONS
					</h3>
					<p className="text-center text-white text-[18px]">
						Details to details is what makes Hexashop different from the other
						themes
					</p>
					<Swiper
						breakpoints={{
							640: {
								slidesPerView: 1,
							},
							768: {
								slidesPerView: 2,
							},
							1199: {
								slidesPerView: 3,
							},
						}}
						spaceBetween={30}
						freeMode={true}
						pagination={{
							clickable: true,
						}}
						navigation={{
							clickable: true,
						}}
						modules={[Pagination, Navigation]}
						className="mySwiper"
					>
						{props.WashingData.data.map((item) => {
							let imgurl = "https://glacial-woodland-47482.herokuapp.com";
							let img =
								item.attributes.img.data.attributes.formats.thumbnail.url;
							// console.log(img);

							return (
								<SwiperSlide key={item.id}>
									<ProductCards
										slug={item.attributes.Model}
										name={item.attributes.Name}
										brands={item.attributes.Brand}
										price={item.attributes.Price}
										Picture={img}
									/>
									;
								</SwiperSlide>
							);
						})}
					</Swiper>
				</div>
			</div>

			<Dlivery />
			<Testimonials />
			
		</div>
	);
};
export async function getServerSideProps(context) {
	let headers = {
		Authorization:
			"9ad861e7d9919e881e8b92dfda4c896c1bac63a983dc0acc82727073cc2692d137929ebae6d3242d3a30f1988bc4b8d59faf909d74751f2d4a4f2ab6e4451fa6b1df48774c83cd3646a9a4fed0c45f2716ffd1fc18fd649ecdeea1107ec31a6762073d70cf6f0baa9e063ddd36cbe04bab635baed591742cba412e3ad64cf1ec",
	};
	let a = await fetch(
		"https://gentle-lake-42463.herokuapp.com/api/products?filters[Category][$eq]=AC&populate=*",
		(headers = headers)
	);
	
	let b = await fetch(
		"https://gentle-lake-42463.herokuapp.com/api/products?filters[Category][$eq]=Freezer&populate=*",
		(headers = headers)
	);
	let c = await fetch(
		"https://gentle-lake-42463.herokuapp.com/api/products?filters[Category][$eq]=Appliance&populate=*",
		(headers = headers)
	);
	let d = await fetch(
		"https://gentle-lake-42463.herokuapp.com/api/products?filters[Category][$eq]=Kitchen&populate=*",
		(headers = headers)
	);
	
	let e = await fetch(
		"https://gentle-lake-42463.herokuapp.com/api/products?filters[Category][$eq]=LED&populate=*",
		(headers = headers)
	);
	let f = await fetch(
		"https://gentle-lake-42463.herokuapp.com/api/products?filters[Category][$eq]=Washing&populate=*",
		(headers = headers)
	);
	

	let productsData = await a.json();
	
	let FreezerData = await b.json();
	let HomeData = await c.json();
	let KitchenData = await d.json();
	let LEDData = await e.json();
	let WashingData = await f.json();

	
	return {
		props: { productsData: productsData, FreezerData: FreezerData,LEDData:LEDData,HomeData:HomeData,KitchenData:KitchenData,WashingData:WashingData},
		// will be passed to the page component as props
	};
}
export default Home;
